name: .NET Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  

    - name: Restore dependencies
      run: dotnet restore  

    - name: Build
      run: dotnet build --configuration Release 

    - name: List files in current directory
      run: ls -R  # Это поможет вам увидеть структуру каталогов

    - name: Run tests
      run: |
        cd src/TestProj 
        dotnet test --configuration Release --no-restore
